Created workpage
netcracker-education-center/collect-and-search-ui pull request #1
Opened 2021-02-17 15:22 UTC by MajorPayne36

- created workpage
- added create request feature
- added modal window for request status

2021-02-17 15:56 UTC, Fuzzzi commented
src/Pages/ff.js  посмотри еще этот файл, он вроде пустой. Зачем мы его коммитим?

2021-02-17 15:57 UTC, Fuzzzi requested changes

2021-02-17 15:57 UTC, Fuzzzi commented on .eslintcache
> +[{"C:\\Users\\админ\\Desktop\\wtf bro\\collect-and-search-ui\\src\\index.js":"1","C:\\Users\\админ\\Desktop\\wtf bro\\collect-and-search-ui\\src\\App.js":"2","C:\\Users\\админ\\Desktop\\wtf bro\\coll
ты уверен, что пути должны быть такие? да и вообще что это за файл, ты уверен, что он должен быть в репозитории?

2021-02-17 15:57 UTC, Fuzzzi commented on src/Components/AddSearchModal.js
> +  // }
а вот это все закомментированное нам точно стоит нести с мастер? если это не нужно - давай не будем коммитить или перенесем в другую ветку

2021-02-17 15:57 UTC, Fuzzzi commented on src/Components/AddSearchModal.js
> +    //   </div>
тоже самое, нужно ли нам это нести в мастер

2021-02-17 17:34 UTC, MajorPayne36 commented on .eslintcache
> +[{"C:\\Users\\админ\\Desktop\\wtf bro\\collect-and-search-ui\\src\\index.js":"1","C:\\Users\\админ\\Desktop\\wtf bro\\collect-and-search-ui\\src\\App.js":"2","C:\\Users\\админ\\Desktop\\wtf bro\\coll
Это файл от линтера для js. Он не нужен, удалил его

2021-02-18 08:12 UTC, Fuzzzi approved these changes

2021-02-18 08:21 UTC, merged