Keycloak
netcracker-education-center/collect-and-search-ui pull request #9
Opened 2021-04-21 20:01 UTC by MajorPayne36

- Added keycloak supporting.
- Redesign user interface.
- Use Ant Design library for render components.

2021-04-22 16:01 UTC, Fuzzzi requested changes

2021-04-22 16:01 UTC, Fuzzzi commented on src/Config.js
> +     url: "http://206.81.22.187:7071", //206.81.22.187
а зачем у нас тут завязка на ip?

2021-04-22 16:01 UTC, Fuzzzi commented on src/Utils/WebSocket.js
> +class WebSocket extends Component {
не готовы же веб сокеты, зачем их тащить в мастер?
давай это оставим в отдельной ветке

2021-04-22 19:09 UTC, MajorPayne36 commented on src/Utils/WebSocket.js
> +class WebSocket extends Component {
Убрал. Скоро все связанное с вебсокетами вынесу в новую ветку

2021-04-23 16:49 UTC, Fuzzzi requested changes

2021-04-23 16:49 UTC, Fuzzzi commented on src/Components/ForWorkpage/Report.jsx
> +    console.log(props.requestId);
лог и  текст

2021-04-26 10:44 UTC, Fuzzzi approved these changes

2021-04-26 10:44 UTC, merged